### PR TITLE
Back up of csbcd configs with a new git repo

### PR DESCRIPTION
**Pull request by ryantanaka**
I reset the git log and made the commits. As for the backup of the csbcd-config folder with the old git repo, I will be zipping it up and posting it in #3.

### CODE REVIEW

**Comment by carlosparadis** [comment]
@ryantanaka The first commit has a .csv file, and I believe we already discussed it in the past, although I don't remember what it was for. If it is not a config, it shouldn't be on the config repo.

**Comment by ryantanaka** [comment]
@carlosparadis , youre right we did. I'll add that to the gitignore and redo the commit

**Comment by ryantanaka** [comment]
@carlosparadis , i accidentally closed this, can you reopen it. 
I've made the changes and pushed them to my repo overwriting the old commit.  It's ready.

**Comment by carlosparadis** [comment]
@ryantanaka I can't open it either! Says "the master branch was force-pushed or recreated".

**Pull request closed without merging**
